version: '3.9'

services:
  container-mitra:
    container_name: container-mitra
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.local
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    ports:
      - "9091:80"
    volumes:
      - .:/var/www/html

  database:
    image: library/mysql:5.7
    command: --sql_mode=""
    restart: unless-stopped
    ports:
      - "4333:3306"
    environment:
      MYSQL_DATABASE: mitra
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  data:
  db-data: