version: '3.9'

services:
  container-mitra:
    container_name: container-mitra
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.local
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    ports:
      - "9091:80"
    volumes:
      - .:/var/www/html

volumes:
  data: